name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.3
      - name: Run Tests
      working-directory: $GITHUB_WORKSPACE
      run: haxe scripts/build.hxml