name: Test

on: [push]

jobs:
  build:
    strategy:
      matrix:
        haxe-version: [4.2.3]
        hxml: [scripts/build.hxml]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ianharrigan/GitHubActionsTest/.github/actions/haxe@master
        with:
          haxe-version: ${{ matrix.haxe-version }}
      - run: haxe ${{ matrix.hxml }}